config/routes.rb
Rails.application.routes.draw do
  resources :dives
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dive.rb
class Dive < ApplicationRecord
  belongs_to :dive_location
  accepts_nested_attributes_for :dive_location, reject_if: :all_blank
end

app/models/dive_location.rb
class DiveLocation < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/dives_controller.rb
class DivesController < ApplicationController
  before_action :set_dive, only: %i[ show edit update destroy ]

  # GET /dives or /dives.json
  def index
    @dives = Dive.all
  end

  # GET /dives/1 or /dives/1.json
  def show
  end

  # GET /dives/new
  def new
    @dive = Dive.new
    @dive.build_dive_location
  end

  # GET /dives/1/edit
  def edit
  end

  # POST /dives or /dives.json
  def create
    @dive = Dive.new(dive_params)

    respond_to do |format|
      if @dive.save
        format.html { redirect_to @dive, notice: "Dive was successfully created." }
        format.json { render :show, status: :created, location: @dive }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dive.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dives/1 or /dives/1.json
  def update
    respond_to do |format|
      if @dive.update(dive_params)
        format.html { redirect_to @dive, notice: "Dive was successfully updated." }
        format.json { render :show, status: :ok, location: @dive }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dive.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dives/1 or /dives/1.json
  def destroy
    @dive.destroy!

    respond_to do |format|
      format.html { redirect_to dives_path, status: :see_other, notice: "Dive was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dive
      @dive = Dive.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def dive_params
      p = params.require(:dive).permit(
        :diver,
        :date,
        :dive_location_id,
        dive_location_attributes: [ :site_name, :location_type, :latitude, :longitude ]
      )

      if params[:dive][:location_selection] == "existing"
        p[:dive_location_attributes] = {}
      end

      p
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dives_helper.rb
module DivesHelper
end

app/views/dive_locations/_dive_location.html.erb
<strong><%= dive_location.site_name %></strong>:
<%= dive_location.location_type %> -
latitude: <%= dive_location.latitude %> -
longitude: <%= dive_location.longitude %>

app/views/dives/_dive.html.erb
<div id="<%= dom_id dive %>">
  <p>
    <strong>Diver:</strong>
    <%= dive.diver %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= dive.date %>
  </p>

  <p>
    <strong>Dive location:</strong>
    <%= render dive.dive_location %>
  </p>

</div>

app/views/dives/_form.html.erb
<%= form_with(model: dive) do |form| %>
  <% if dive.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(dive.errors.count, "error") %> prohibited this dive from being saved:</h2>

      <ul>
        <% dive.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :diver, style: "display: block" %>
    <%= form.text_field :diver %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <h2>Dive Location</h2>

  <div data-controller="existing-or-new">
    <div>
      <%= form.radio_button :location_selection, 'existing',
          checked: true,
          data: {
            existing_or_new_target: "radio",
            action: "change->existing-or-new#toggle"
          } %>
      <%= form.label :location_selection_existing, 'Select Existing Location' %>

      <%= form.radio_button :location_selection, 'new',
          data: {
            existing_or_new_target: "radio",
            action: "change->existing-or-new#toggle"
          } %>
      <%= form.label :location_selection_new, 'Create New Location' %>
    </div>

    <div id="existing_location_fields" data-existing-or-new-target="existing">
      <%= form.label :dive_location_id, 'Select Location', style: "display: block" %>
      <%= form.collection_select :dive_location_id, DiveLocation.all, :id, :site_name %>
    </div>

    <div id="new_location_fields" data-existing-or-new-target="new" style="display: none;">
      <%= form.fields_for :dive_location do |dive_location_form| %>
        <div>
          <%= dive_location_form.label :site_name, style: "display: block" %>
          <%= dive_location_form.text_field :site_name %>
        </div>

        <div>
          <%= dive_location_form.label :location_type, style: "display: block" %>
          <%= dive_location_form.text_field :location_type %>
        </div>

        <div>
          <%= dive_location_form.label :latitude, style: "display: block" %>
          <%= dive_location_form.text_field :latitude %>
        </div>

        <div>
          <%= dive_location_form.label :longitude, style: "display: block" %>
          <%= dive_location_form.text_field :longitude %>
        </div>
      <% end %>
    </div>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/dives/edit.html.erb
<% content_for :title, "Editing dive" %>

<h1>Editing dive</h1>

<%= render "form", dive: @dive %>

<br>

<div>
  <%= link_to "Show this dive", @dive %> |
  <%= link_to "Back to dives", dives_path %>
</div>

app/views/dives/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Dives" %>

<h1>Dives</h1>

<div id="dives">
  <% @dives.each do |dive| %>
    <%= render dive %>
    <p>
      <%= link_to "Show this dive", dive %>
    </p>
  <% end %>
</div>

<%= link_to "New dive", new_dive_path %>

app/views/dives/new.html.erb
<% content_for :title, "New dive" %>

<h1>New dive</h1>

<%= render "form", dive: @dive %>

<br>

<div>
  <%= link_to "Back to dives", dives_path %>
</div>

app/views/dives/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @dive %>

<div>
  <%= link_to "Edit this dive", edit_dive_path(@dive) %> |
  <%= link_to "Back to dives", dives_path %>

  <%= button_to "Destroy this dive", @dive, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Accept Nested Attributes" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>